name: aiffel workflow

on: [push] # push될 때 마다 작동

jobs:
  Test:

    runs-on: ubuntu-latest # 우분투 최신 버전으로 실행

    steps:
      # Hello, Aiffel 출력
      - name: echo Hello, Aiffel
        run: echo Hello, Aiffel
        
      # 현재 위치 출력
      - name: pwd
        run: pwd   
        
      # 현재 위치의 리스트 출력
      - name: ls
        run: ls
